version: "3"
services:
  postgres:
    image: postgis/postgis:14-3.3-alpine
    environment:
      - POSTGRES_USER=sppnaut
      - POSTGRES_PASSWORD=sppnaut
      - POSTGRES_DB=sppnaut
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
    volumes:
      - ./pgdata:/var/lib/postgresql/data:delegated
    ports:
      - 5434:5432
