name: Build and test

runs:
  using: composite

  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' # https://github.com/actions/setup-python/issues/571
        cache: 'pip'
    - name: Install GIS Packages
      shell: bash
      run: |
        sudo apt-get install gdal-bin
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-versions'
        cache: 'npm'
    - name: Build assets
      shell: bash
      run: |
        npm ci
        npm run build
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --require-hashes --no-deps -r requirements.txt -r dev-requirements.txt
    - name: Run Tests
      shell: bash
      run: |
        pytest unit_tests
