# Generated by Django 4.1.7 on 2023-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s127", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullPilotageDistrictProxy",
            fields=[],
            options={
                "verbose_name": "Pilotage district (full form)",
                "verbose_name_plural": "Pilotages district (full form)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("s127.pilotagedistrict",),
        ),
        migrations.CreateModel(
            name="SimplePilotageDistrictProxy",
            fields=[],
            options={
                "verbose_name": "Pilotage district (simple form)",
                "verbose_name_plural": "Pilotages district (simple form)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("s127.pilotagedistrict",),
        ),
        migrations.AddField(
            model_name="pilotservice",
            name="pilot_boarding_places",
            field=models.ManyToManyField(to="s127.pilotboardingplace"),
        ),
    ]
