# Generated by Django 4.1.9 on 2023-05-25 23:12

import carting.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s127", "0003_contactdetails_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullPilotServiceProxy",
            fields=[],
            options={
                "verbose_name": "Pilot service (full form)",
                "verbose_name_plural": "Pilot services (full form)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("s127.pilotservice",),
        ),
        migrations.AlterField(
            model_name="applicability",
            name="category_of_dangerous_or_hazardous_cargo",
            field=carting.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "IMDG Code Class 1 Div. 1.1",
                            "Explosives, Division 1: substances and articles which have a mass explosion hazard",
                        ),
                        (
                            "IMDG Code Class 1 Div. 1.2",
                            "Explosives, Division 2: substances and articles which have a projection hazard but not a mass explosion hazard",
                        ),
                        (
                            "IMDG Code Class 1 Div. 1.3",
                            "Explosives, Division 3: substances and articles which have a fire hazard and either a minor blast hazard or a minor projection hazard or both, but not a mass explosion hazard",
                        ),
                        (
                            "IMDG Code Class 1 Div. 1.4",
                            "Explosives, Division 4: substances and articles which present no significant hazard",
                        ),
                        (
                            "IMDG Code Class 1 Div. 1.5",
                            "Explosives, Division 5: very insensitive substances which have a mass explosion hazard",
                        ),
                        (
                            "IMDG Code Class 1 Div. 1.6",
                            "Explosives, Division 6: extremely insensitive articles which do not have a mass explosion hazard",
                        ),
                        ("IMDG Code Class 2 Div. 2.1", "Gases, flammable gases"),
                        (
                            "IMDG Code Class 2 Div. 2.2",
                            "Gases, non-flammable, non-toxic gases",
                        ),
                        ("IMDG Code Class 2 Div. 2.3", "Gases, toxic gases"),
                        ("IMDG Code Class 3", "flammable liquids"),
                        (
                            "IMDG Code Class 4 Div. 4.1",
                            "flammable solids, self-reactive substances and desensitized explosives",
                        ),
                        (
                            "IMDG Code Class 4 Div. 4.2",
                            "substances liable to spontaneous combustion",
                        ),
                        (
                            "IMDG Code Class 4 Div. 4.3",
                            "substances which, in contact with water, emit flammable gases",
                        ),
                        ("IMDG Code Class 5 Div. 5.1", "oxidizing substances"),
                        ("IMDG Code Class 5 Div. 5.2", "organic peroxides"),
                        ("IMDG Code Class 6 Div. 6.1", "toxic substances"),
                        ("IMDG Code Class 6 Div. 6.2", "infectious substances"),
                        ("IMDG Code Class 7", "Radioactive material"),
                        ("IMDG Code Class 8", "Corrosive substances"),
                        (
                            "IMDG Code Class 9",
                            "Miscellaneous dangerous substances and articles",
                        ),
                        (
                            "Harmful Substances in packaged form",
                            "Harmful Substances In Packaged Form",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                help_text="Classification of dangerous goods or hazardous materials based on the International Maritime Dangerous Goods Code (<a href='https://www.imo.org/fr/OurWork/Safety/Pages/DangerousGoods-default.aspx' target='_blank'>IMDG Code</a>)",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="contactdetails",
            name="communication_channel",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="A channel number assigned to a specific radio frequency, frequencies or frequency band.<br/>Separate multiple values with a comma.<br/>",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="noticetime",
            name="notice_time_hours",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DurationField(),
                blank=True,
                default=list,
                help_text="Format : hh:mm:ss <br/>Separate multiple values with a comma.<br/>The time duration prior to the time the service is needed, when notice must be provided to the service provider.<br/>",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="pilotagedistrict",
            name="communication_channel",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="A channel number assigned to a specific radio frequency, frequencies or frequency band.<br/>Separate multiple values with a comma.<br/>",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="pilotboardingplace",
            name="communication_channel",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="A channel number assigned to a specific radio frequency, frequencies or frequency band.<br/>Separate multiple values with a comma.<br/>",
                size=None,
            ),
        ),
    ]
