# Generated by Django 4.1.9 on 2023-05-25 13:41

import carting.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("s127", "0005_alter_contactdetails_communication_channel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radiocommunications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_of_comm_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("preferred calling", "Preferred Calling"),
                            ("alternate calling", "Alternate Calling"),
                            ("preferred working", "Preferred Working"),
                            ("alternate working", "Alternate Working"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category_of_maritime_broadcast",
                    carting.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("navigational warning", "Navigational Warning"),
                                ("meteorological warning", "Meteorological Warning"),
                                ("ice report", "Ice Report"),
                                ("SAR information", "Sar Information"),
                                ("pirate attack warning", "Pirate Attack Warning"),
                                ("meteorological forecast", "Meteorological Forecast"),
                                ("pilot service message", "Pilot Service Message"),
                                ("AIS information", "Ais Information"),
                                ("LORAN message", "Loran Message"),
                                ("SATNAV message", "Satnav Message"),
                                ("gale warning", "Gale Warning"),
                                ("storm warning", "Storm Warning"),
                                (
                                    "tropical revolving storm warning",
                                    "Tropical Revolving Storm Warning",
                                ),
                                ("NAVAREA warning", "Navarea Warning"),
                                ("coastal warning", "Coastal Warning"),
                                ("local warning", "Local Warning"),
                                (
                                    "low water level warning/negative tidal surge",
                                    "Low Water Level Warning Negative Tidal Surge",
                                ),
                                ("icing warning", "Icing Warning"),
                                ("tsunami broadcast", "Tsunami Broadcast"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        default=list,
                        help_text="Classification of maritime broadcast based on the nature of information conveyed.",
                        size=None,
                    ),
                ),
                (
                    "category_of_radio_methods",
                    carting.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "Low Frequency (LF) voice traffic",
                                    "Low Frequency Lf Voice Traffic",
                                ),
                                (
                                    "Medium Frequency (MF) voice traffic",
                                    "Medium Frequency Mf Voice Traffic",
                                ),
                                (
                                    "High Frequency (HF) voice traffic",
                                    "High Frequency Hf Voice Traffic",
                                ),
                                (
                                    "Very High Frequency (VHF) voice traffic",
                                    "Very High Frequency Vhf Voice Traffic",
                                ),
                                (
                                    "High Frequency Narrow Band Direct Printing",
                                    "High Frequency Narrow Band Direct Printing",
                                ),
                                ("NAVTEX", "Navtex"),
                                ("SafetyNET", "Safety Net"),
                                (
                                    "NBDP Telegraphy (Narrow Band Direct Printing Telegraphy)",
                                    "Nbdp Telegraphy Narrow Band Direct Printing Telegraphy",
                                ),
                                ("facsimile", "Facsimile"),
                                ("NAVIP", "Navip"),
                                (
                                    "Low Frequency (LF) digital traffic",
                                    "Low Frequency Lf Digital Traffic",
                                ),
                                (
                                    "Medium Frequency (MF) digital traffic",
                                    "Medium Frequency Mf Digital Traffic",
                                ),
                                (
                                    "High Frequency (HF) digital traffic",
                                    "High Frequency Hf Digital Traffic",
                                ),
                                (
                                    "Very High Frequency (VHF) digital traffic",
                                    "Very High Frequency Vhf Digital Traffic",
                                ),
                                (
                                    "Low Frequency (LF) telegraph traffic",
                                    "Low Frequency Lf Telegraph Traffic",
                                ),
                                (
                                    "Medium Frequency (MF) telegraph traffic",
                                    "Medium Frequency Mf Telegraph Traffic",
                                ),
                                (
                                    "High Frequency (HF) telegraph traffic",
                                    "High Frequency Hf Telegraph Traffic",
                                ),
                                (
                                    "Medium Frequency (MF) Digital Selective Call traffic",
                                    "Medium Frequency Mf Digital Selective Call Traffic",
                                ),
                                (
                                    "High Frequency (HF) Digital Selective Call traffic",
                                    "High Frequency Hf Digital Selective Call Traffic",
                                ),
                                (
                                    "Very High Frequency (VHF) Digital Selective Call traffic",
                                    "Very High Frequency Vhf Digital Selective Call Traffic",
                                ),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        default=list,
                        help_text="Categories of radiocommunications based on frequency band and radio traffic method.",
                        size=None,
                    ),
                ),
                (
                    "communication_channel",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="A channel number assigned to a specific radio frequency, frequencies or frequency band.<br/>ℹ️ Write comma separated values to define multiple.",
                        size=None,
                    ),
                ),
                (
                    "contact_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Supplemental instructions on how or when to contact the individual, organisation, or service",
                        null=True,
                    ),
                ),
                (
                    "signal_frequency",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "transmission_content",
                    models.CharField(
                        blank=True,
                        help_text="Content of transmission. Remarks: Not to be used if CATMAB is populated",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiocommunications",
                        to="s127.contactdetails",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FrequencyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.BigIntegerField()),
                (
                    "frequency_shore_station_transmits",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="The shore station transmitter frequency expressed in kHz to one decimal place. Units: kHZ, Resolution: 0.1, Format: XXXXXX Examples: 4379.1 kHz becomes 043791; 13162.8 kHz becomes 131628",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "frequency_shore_station_receives",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="The shore station receiver frequency expressed in kHz to one decimal place. Units: kHz, Resolution: 0.1, Format: XXXXXX Examples: 4379.1 kHz becomes 043791; 13162.8 kHz becomes 131628",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "contact_instructions",
                    models.TextField(
                        blank=True,
                        help_text="Supplemental instructions on how or when to contact the individual, organisation, or service",
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
