# Generated by Django 4.1.9 on 2023-05-26 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("s127", "0005_radiocommunications_frequencypair"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="radiocommunications",
            options={"verbose_name_plural": "Radiocommunications"},
        ),
        migrations.RemoveField(
            model_name="radiocommunications",
            name="category_of_maritime_broadcast",
        ),
        migrations.RemoveField(
            model_name="radiocommunications",
            name="category_of_radio_methods",
        ),
        migrations.RemoveField(
            model_name="radiocommunications",
            name="signal_frequency",
        ),
        migrations.RemoveField(
            model_name="radiocommunications",
            name="transmission_content",
        ),
    ]
