# Generated by Django 4.1.9 on 2023-05-29 18:38

from django.db import migrations
import s100.models


class Migration(migrations.Migration):
    dependencies = [
        ("s127", "0006_alter_radiocommunications_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilotservice",
            name="geometry",
            field=s100.models.GMMultiSurface(blank=True, null=True, srid=4326),
        ),
    ]
