# Generated by Django 4.2.2 on 2023-06-29 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s127", "0007_delete_fullpilotagedistrictproxy_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE s127_pilotservice_pilot_boarding_places RENAME TO s127_pilotboardingplaceservicethrough",
                    reverse_sql="ALTER TABLE s127_pilotboardingplaceservicethrough RENAME TO s127_pilotservice_pilot_boarding_places",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE s127_pilotboardingplaceservicethrough RENAME pilotservice_id TO pilot_service_id",
                    reverse_sql="ALTER TABLE s127_pilotboardingplaceservicethrough RENAME pilot_service_id TO pilotservice_id",
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE s127_pilotboardingplaceservicethrough RENAME pilotboardingplace_id TO pilot_boarding_place_id",
                    reverse_sql="ALTER TABLE s127_pilotboardingplaceservicethrough RENAME pilot_boarding_place_id to pilotboardingplace_id",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PilotBoardingPlaceServiceThrough",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "pilot_boarding_place",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="s127.pilotboardingplace",
                            ),
                        ),
                        (
                            "pilot_service",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="s127.pilotservice",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="pilotservice",
                    name="pilot_boarding_places",
                    field=models.ManyToManyField(
                        through="s127.PilotBoardingPlaceServiceThrough",
                        to="s127.pilotboardingplace",
                    ),
                ),
            ],
        )
    ]
