# Generated by Django 4.1.9 on 2023-06-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s127", "0007_delete_fullpilotagedistrictproxy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardingPlaceServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pilot_boarding_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s127.pilotboardingplace",
                    ),
                ),
                (
                    "pilot_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="s127.pilotservice",
                    ),
                ),
            ],
        ),
        # FIXME: On va perdre toutes les connexions
        migrations.RemoveField(
            model_name="pilotservice",
            name="pilot_boarding_places",
        ),
        migrations.AddField(
            model_name="pilotservice",
            name="pilot_boarding_places",
            field=models.ManyToManyField(
                through="s127.BoardingPlaceServiceProvider",
                to="s127.pilotboardingplace",
            ),
        ),
    ]
