name: Pull request

on:
  pull_request:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:14-3.3-alpine
        env:
          POSTGRES_USER: sppnaut
          POSTGRES_PASSWORD: sppnaut
          POSTGRES_DB: sppnaut
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 50
        ports:
          - 5434:5432

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install GIS Packages
        run: |
          sudo apt-get install gdal-bin
      - name: Build assets
        run: |
          npm ci
          npm run build
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes --no-deps -r requirements.txt -r dev-requirements.txt
      - name: Run Tests
        run: |
          pytest unit_tests
