name: Pull request

on:
  pull_request:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes --no-deps -r requirements.txt -r dev-requirements.txt
      - name: Run Tests
        run: |
          pytest unit_tests
