name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Run Tests
        run: |
          pytest unit_tests

  deploy:
    name: Deploy to Clever Cloud
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      # This action requires an unshallow working copy,
      # so the following prerequisites are necessary:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Deploy your application
      - uses: 47ng/actions-clever-cloud@v1.2.0
        with:
          appID: app_62a6232b-6030-4ad4-a177-d24ff1f99d76
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
