name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:14-3.3-alpine
        env:
          POSTGRES_USER: sppnaut
          POSTGRES_PASSWORD: sppnaut
          POSTGRES_DB: sppnaut
        options: >-
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 50
        ports:
          - 5434:5432

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build_and_test

  deploy:
    name: Deploy to Clever Cloud
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      # This action requires an unshallow working copy,
      # so the following prerequisites are necessary:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Deploy your application
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: app_62a6232b-6030-4ad4-a177-d24ff1f99d76
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
