name: Test deploy in staging

on:
  pull_request:

jobs:
  deploy:
    name: Deploy to Clever Cloud
    runs-on: ubuntu-latest
    steps:
      # This action requires an unshallow working copy,
      # so the following prerequisites are necessary:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Deploy your application
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: app_819020b2-14e7-4f94-a152-3331fe7ae76b
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
