# Generated by Django 4.1.5 on 2023-02-14 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="INSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bpn_id", models.CharField(max_length=40, unique=True)),
                (
                    "numero",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("content", models.TextField(blank=True, default=None, null=True)),
                (
                    "typology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OUVRAGE", "ouvrage"),
                            ("CHAPTER", "chapitre"),
                            ("SUBCHAPTER", "sChapitre"),
                            ("PARAGRAPH", "para"),
                            ("SUBPARAGRAPH", "sPara"),
                            ("SUBSUBPARAGRAPH", "ssPara"),
                            ("ALINEA", "alinea"),
                            ("REFERENCE", "texte/reference"),
                            ("TOPONYME", "texte/principal"),
                            ("TABLE", "tableau"),
                            ("ILLUSTRATION", "illustration"),
                        ],
                        default=None,
                        max_length=25,
                        null=True,
                    ),
                ),
                ("xpath", models.CharField(max_length=512)),
                ("ouvrage_name", models.CharField(max_length=10)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
