# Generated by Django 4.1.4 on 2023-02-01 14:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bpn_id", models.CharField(max_length=32)),
                ("content", models.TextField()),
                (
                    "typology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OUVRAGE", "Ouvrage"),
                            ("CHAPTER", "Chapter"),
                            ("SUBCHAPTER", "Sub chapter"),
                            ("PARAGRAPH", "Paragraph"),
                            ("SUBPARAGRAPH", "SubParagraph"),
                            ("SUBSUBPARAGRAPH", "SubSubParagraph"),
                            ("ALINEA", "Alinea"),
                            ("REFERENCE", "Reference"),
                            ("TOPONYME", "Topomyne"),
                            ("TABLE", "Table"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                ("xpath", models.CharField(max_length=511)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
