# Generated by Django 4.1.7 on 2023-03-09 08:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BDGS",
            fields=[
                (
                    "inspire_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=50)),
                ("raw", models.JSONField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ouvragesection",
            name="typology",
            field=models.CharField(
                choices=[
                    ("OUVRAGE", "ouvrage"),
                    ("CHAPTER", "chapitre"),
                    ("SUBCHAPTER", "sChapitre"),
                    ("PARAGRAPH", "para"),
                    ("SUBPARAGRAPH", "sPara"),
                    ("SUBSUBPARAGRAPH", "ssPara"),
                    ("ALINEA", "alinea"),
                    ("TABLE", "tableau"),
                    ("ILLUSTRATION", "illustration"),
                    ("TOPONYME", "texte/principal|liste/texte/principal"),
                    ("REFERENCE", "texte/reference|liste/texte/reference"),
                ],
                max_length=25,
            ),
        ),
    ]
