# Generated by Django 4.1.7 on 2023-03-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ouvragesection",
            name="typology",
            field=models.CharField(
                choices=[
                    ("OUVRAGE", "Ouvrage"),
                    ("CHAPTER", "Chapter"),
                    ("SUBCHAPTER", "Subchapter"),
                    ("PARAGRAPH", "Paragraph"),
                    ("SUBPARAGRAPH", "Subparagraph"),
                    ("SUBSUBPARAGRAPH", "Subsubparagraph"),
                    ("ALINEA", "Alinea"),
                    ("TABLE", "Table"),
                    ("ILLUSTRATION", "Illustration"),
                    ("TOPONYME", "Toponyme"),
                    ("REFERENCE", "Reference"),
                ],
                max_length=25,
            ),
        ),
    ]
