# Generated by Django 4.1.5 on 2023-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="element",
            name="numero",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="element",
            name="typology",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OUVRAGE", "ouvrage"),
                    ("CHAPTER", "chapitre"),
                    ("SUBCHAPTER", "sChapitre"),
                    ("PARAGRAPH", "para"),
                    ("SUBPARAGRAPH", "sPara"),
                    ("SUBSUBPARAGRAPH", "ssPara"),
                    ("ALINEA", "alinea"),
                    ("REFERENCE", "reference"),
                    ("TOPONYME", "principal"),
                    ("TABLE", "tableau"),
                    ("ILLUSTRATION", "illustration"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
