# Generated by Django 4.0.8 on 2023-02-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carting', '0002_init_insection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insection',
            name='bpn_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
