# Generated by Django 4.1.7 on 2023-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0003_bdgs_alter_ouvragesection_typology"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bdgs",
            options={"verbose_name": "BDGS", "verbose_name_plural": "BDGS"},
        ),
        migrations.AlterField(
            model_name="bdgs",
            name="category",
            field=models.CharField(max_length=255),
        ),
    ]
