# Generated by Django 4.1.7 on 2023-03-10 09:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0003_alter_ouvragesection_typology"),
    ]

    operations = [
        migrations.CreateModel(
            name="BDGS",
            fields=[
                (
                    "inspire_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=255)),
                ("raw", models.JSONField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "BDGS",
                "verbose_name_plural": "BDGS",
            },
        ),
    ]
