# Generated by Django 4.1.5 on 2023-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carting", "0003_element_numero_alter_element_typology"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="bpn_id",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
