# Generated by Django 4.1.7 on 2023-03-31 08:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0003_alter_ouvragesection_typology"),
    ]

    operations = [
        migrations.CreateModel(
            name="S1xyObject",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("typology", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, default=None, null=True, srid=4326
                    ),
                ),
                (
                    "link_to",
                    models.ManyToManyField(blank=True, to="carting.s1xyobject"),
                ),
            ],
        ),
    ]
