# Generated by Django 4.1.7 on 2023-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0004_s1xyobject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="s1xyobject",
            name="link_to",
            field=models.ManyToManyField(blank=True, to="carting.s1xyobject"),
        ),
    ]
