# Generated by Django 4.1.5 on 2023-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carting", "0004_alter_element_bpn_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="typology",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OUVRAGE", "ouvrage"),
                    ("CHAPTER", "chapitre"),
                    ("SUBCHAPTER", "sChapitre"),
                    ("PARAGRAPH", "para"),
                    ("SUBPARAGRAPH", "sPara"),
                    ("SUBSUBPARAGRAPH", "ssPara"),
                    ("ALINEA", "alinea"),
                    ("REFERENCE", "texte/reference"),
                    ("TOPONYME", "texte/principal"),
                    ("TABLE", "tableau"),
                    ("ILLUSTRATION", "illustration"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
