# Generated by Django 4.1.7 on 2023-03-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0004_bdgs"),
    ]

    operations = [
        migrations.AddField(
            model_name="ouvragesection",
            name="bdgs_object",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="carting.bdgs",
            ),
        ),
    ]
