# Generated by Django 4.1.7 on 2023-04-20 13:30

import carting.models.s127
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0005_alter_featurename_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilotboardingplace",
            name="status",
            field=carting.models.s127.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("permanent", "Permanent"),
                        ("occasional", "Occasional"),
                        ("recommended", "Recommended"),
                        ("not in use", "Not In Use"),
                        ("periodic/intermittent", "Periodic Intermittent"),
                        ("reserved", "Reserved"),
                        ("temporary", "Temporary"),
                        ("private", "Private"),
                        ("mandatory", "Mandatory"),
                        ("extinguished", "Extinguished"),
                        ("illuminated", "Illuminated"),
                        ("historic", "Historic"),
                        ("public", "Public"),
                        ("synchronised", "Synchronised"),
                        ("watched", "Watched"),
                        ("un-watched", "Un Watched"),
                        ("existence doubtful", "Existence Doubtful"),
                        ("buoyed", "Buoyed"),
                    ],
                    max_length=255,
                    null=True,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
