# Generated by Django 4.1.7 on 2023-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0005_alter_applicability_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicability",
            name="in_ballast",
            field=models.BooleanField(
                blank=True,
                choices=[(None, "---------"), (True, "Yes"), (False, "No")],
                help_text="Whether the vessel is in ballast.",
                null=True,
            ),
        ),
    ]
