# Generated by Django 4.1.7 on 2023-04-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carting", "0006_alter_applicability_in_ballast_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="language",
            field=models.CharField(
                choices=[("fra", "French"), ("eng", "English")],
                default="fra",
                max_length=3,
            ),
        ),
    ]
