# Generated by Django 4.1.7 on 2023-04-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("carting", "0007_alter_information_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicability",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="applicability",
            name="object_id",
        ),
        migrations.CreateModel(
            name="PermissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_of_relationship",
                    models.CharField(
                        choices=[
                            ("prohibited", "Prohibited"),
                            ("not recommended", "Not Recommended"),
                            ("permitted", "Permitted"),
                            ("recommended", "Recommended"),
                            ("required", "Required"),
                            ("not required", "Not Required"),
                        ],
                        max_length=255,
                    ),
                ),
                ("feature_object_id", models.BigIntegerField()),
                ("applicability_object_id", models.BigIntegerField()),
                (
                    "applicability_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "feature_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
